### ISSUE TITLE
Operate First Community - Broken link for "Operate First Community Handbook"

### ISSUE THREAD

**Issue by tinaafitz** [operate-first/training#16]
Found a broken link while reading about Operate First. 

Here's the page:
[Check out the Operate First Community Handbook](https://www.operate-first.cloud/community-handbook/)
![OF_broken_link](https://user-images.githubusercontent.com/109132/194570917-51d9e135-67b9-41b1-a497-cde95f419e90.png)

Which results in an error:
![OF_broken_link_error](https://user-images.githubusercontent.com/109132/194571103-5f4c045f-b888-4327-9311-c911e4c4ff4f.png)

**Comment by schwesig** [comment]
/assign @schwesig 

@tinaafitz, thanks for finding this

**Comment by tinaafitz** [comment]
Thanks @schwesig, I'm happy to help. :-)

**Comment by schwesig** [comment]
https://www.operate-first.cloud/docs-training
--> [Introduction to Operate First](https://www.operate-first.cloud/training/operate_first_intro) -->
--> left bar: [Operate First community](https://www.operate-first.cloud/training/operate_first_intro/community_vision.html#)
--> link at bottom [Check out the Operate First Community Handbook](https://www.operate-first.cloud/community-handbook/)
