### ISSUE TITLE
Publishing pipeline for `training` repo

### ISSUE THREAD

**Issue by quaid** [operate-first/training#7]

**Comment by HumairAK** [comment]
@stefwrite can you update the requirements / flesh out the details of what's required here?

**Comment by stefwrite** [comment]
When we accept a PR to the "training" repo, automation should:

1. Build index.md into an HTML at `operate-first.cloud/training/index.html`

2. For each subdirectory under the `courses` directory:

- Confirm that it has a `_toc.yaml` file (is a Jupyter Book). If so, continue with the next steps; if not go on to the next subdirectory.
- Run Jupyter Book to build the contents into a book. To do this, run this command from courses (parent) directory: 
`jupyter-book build <subdirectory_name>`
- By default, the output is created under a new `_build` directory under that subdirectory. Publish the contents of this subdirectory under the website's `operate-first.cloud/training/` directory. Use the same name as the course's subdirectory in the repo:
`cp -r my-course/_build <path_to_website_files>/training/my-course`

**Comment by durandom** [comment]
fixed in #9
